### ISSUE TITLE
dependency conflicts when install programl

### ISSUE THREAD

**Issue by alienwan34** [UCLA-VAST/GNN-DSE#3]
![1680776641555](https://user-images.githubusercontent.com/18711612/230350121-c646738c-f636-4d28-aeef-2f76ebc526b7.png)
the requirements.txt for GNN-DSE requires tensorflow 2.2.1 which requires numpy < 1.19.0, but the programl requires numpy >= 1.19.3, . How can i solve this problem.

**Comment by SyedaMunazza** [comment]
how you solved this issue kindly tell
