### ISSUE TITLE
error when  generating graph 

### ISSUE THREAD

**Issue by alienwan34** [UCLA-VAST/GNN-DSE#4]
When i run the command python3 -W ignore graph-gen.py, it reports an error as following:
![1681461112974](https://user-images.githubusercontent.com/18711612/231989859-94f8656f-7cea-40aa-9191-e29a4f48a52c.png)
This is because the order of functions in the C code is inconsistent with that in the generated llvm IR (xx.ll), thus resulting a wrong match of loops  in graph-gen.py. I notice that the given example 'aes' also shows the problem when running graph-gen.py. So how is the final graph (with pragma node) under the 'programl/processed' directory correctly generated ?

**Comment by SyedaMunazza** [comment]
I also need help to run this code. Kindly tell me which Python version used for it because installing dependencies shows lots of conflicts . Waiting for your answer I will be grateful .Thanks

**Comment by atefehsz** [comment]
The graph generator for multiple functions is not open-sourced yet.
The project was done with Python3.6 but is runnable with other versions as well. You can discard the version number of packages if it doesn't work for you.

**Comment by atefehsz** [comment]
Update the graph gen file.

**Comment by Lining1127** [comment]
Hi, I have a problem with the implementation of the GNN-DSE code, can you help to solve it?

db_paths for gemver:
../dse_database/poly/databases/gemver_result_updated-0.db
f_db is **:    <_io.BufferedReader name='../dse_database/poly/databases/gemver_result_updated-0.db'>
<class '_io.BufferedReader'>
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                          | 17/24 [00:13<00:05,  1.23it/s]
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    dataset, pragma_dim = get_data_list()
  File "/home/psdz/lining/GNN-DSE-main/src/programl_data.py", line 270, in get_data_list
    data = pickle.load(f_db)
_pickle.UnpicklingError: invalid load key, '\x00'.
Error when pickle.load() tries to load  gemver_result_updated-0.db .
Thanks for your help.
