### ISSUE TITLE
Error when generating graph invoking programl

### ISSUE THREAD

**Issue by w6225656** [UCLA-VAST/GNN-DSE#5]
When I try to generate graph using programl, say
graph_generator(kernel, path, BENCHMARK, generate_programl = True)
the using of commands llvm2graph and graph2json in programl_script.sh meets some troubles.
I have already installed programl 0.3.2. How can I use these two commands of it?

####################
now processing aes
/home/qinaox/GNN-DSE/GNN-DSE/dse_database/programl_script.sh: line 3: llvm2graph: command not found
/home/qinaox/GNN-DSE/GNN-DSE/dse_database/programl_script.sh: line 4: graph2json: command not found
Traceback (most recent call last):
  File "graph_gen.py", line 439, in <module>
    graph_generator(kernel, path, BENCHMARK, generate_programl = True)
  File "graph_gen.py", line 390, in graph_generator
    g_nx = read_json_graph(join(path, name))
  File "graph_gen.py", line 78, in read_json_graph
    js_graph=json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by atefehsz** [comment]
This is the Git commit hash of the PrograML project that was used here: 06e9256. Alternatively, you can use the graph generator of our [HARP](https://github.com/UCLA-VAST/HARP) project that uses PrograML Python APIs.

**Comment by w6225656** [comment]
Thanks for your kind reply. It works with the PrograML Python APIs.
